version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/Users/mmornati/certs:/etc/nginx/certs:ro"
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/Users/mmornati/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/Users/mmornati/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  blog:
    image: mmornati/docker-ghostblog
    container_name: blog
    ports:
      - 127.0.0.1:2368:2368
    volumes:
      - /Users/mmornati/ghost-blog:/ghost-override
    environment:
      - VIRTUAL_HOST=your.virtualhost.net
      - WEB_URL=https://your.virtualhost.net
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=2368
      - CLOUDINARY_URL=cloudinary://key@your-virtualhost-net
      - LETSENCRYPT_HOST=your.virtualhost.net
      - LETSENCRYPT_EMAIL=your@email.net
